# Generated by Django 4.1.7 on 2023-04-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=48)),
                ('apellidos', models.CharField(max_length=48)),
                ('identificacion', models.IntegerField()),
                ('celular', models.BigIntegerField()),
                ('tipo_usuario', models.CharField(max_length=48)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
                ('saldo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
