# Generated by Django 4.1.7 on 2023-05-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20230501_1651'),
    ]

    operations = [
    ]
