# Generated by Django 4.1.7 on 2023-04-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='Usuarios/img/Perfil/default.png', upload_to='Usuarios/img/Perfil/'),
        ),
    ]
