# Generated by Django 4.1.7 on 2023-05-01 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuarios', '0003_auto_20230501_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_usuario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dependencia', models.PositiveIntegerField(unique=True)),
                ('nombre_dependencia', models.CharField(max_length=50)),
                ('tipo_dependencia', models.CharField(choices=[('Financiera', 'Financiera'), ('Otra', 'Otra')], max_length=50)),
                ('saldo_dependencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultima_actualizacion_dependencia', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_usuario', models.CharField(max_length=50)),
                ('apellidos_usuario', models.CharField(max_length=50)),
                ('identificacion_usuario', models.PositiveIntegerField(unique=True)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('foto_perfil_usuario', models.ImageField(blank=True, default='Usuarios/img/Perfil/default.png', upload_to='Usuarios/img/Perfil')),
                ('amigos_usuario', models.ManyToManyField(blank=True, to='Usuarios.usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_factura_dependencia', models.CharField(max_length=100)),
                ('monto_transaccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento_transaccion', models.DateTimeField(blank=True, null=True)),
                ('pagada_transaccion', models.BooleanField(default=False)),
                ('dependencia_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_enviadas', to='Usuarios.dependencia')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_recibidas', to='Usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_semestre_estudiante', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creditos_registrados_estudiante', models.PositiveIntegerField()),
                ('semestre_actual_estudiante', models.PositiveIntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_envio', models.PositiveIntegerField(unique=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('monto_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_envio', models.BooleanField(default=False)),
                ('destino_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_recibidos', to='Usuarios.cuenta')),
                ('origen_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_realizados', to='Usuarios.cuenta')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
        ),
        migrations.AddField(
            model_name='dependencia',
            name='usuarios_dependencia',
            field=models.ManyToManyField(blank=True, related_name='dependencias', to='Usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='usuario_cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='Usuarios.usuario'),
        ),
    ]
