# Generated by Django 4.1.7 on 2023-05-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='semestre_actual_estudiante',
            new_name='semestre_a_pagar_estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_a_pagar_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_a_pagar_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_limite_a_pagar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
