# Generated by Django 4.1.9 on 2023-05-17 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Usuarios', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiera',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('saldo_financiera', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultima_actualizacion_financiera', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financiera',
                'verbose_name_plural': 'Financieras',
            },
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='usuario_cuenta',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='semestre_actual_estudiante',
            new_name='semestre_a_pagar_estudiante',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='usuario_destino',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='amigos_usuario',
            new_name='amigos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos_usuario',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email_usuario',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='foto_perfil_usuario',
            new_name='foto_perfil',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='identificacion_usuario',
            new_name='identificacion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres_usuario',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='dependencia_origen',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='origen',
            field=models.CharField(choices=[('financiera', 'Financiera'), ('usuario', 'Usuario')], default='financiera', max_length=10),
        ),
        migrations.DeleteModel(
            name='Dependencia',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='financiera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_enviadas', to='Usuarios.financiera'),
        ),
    ]
