# Generated by Django 4.1.7 on 2023-04-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='Usuarios/img/Perfil/default.png', upload_to='Usuarios/img/Perfil'),
        ),
    ]
