# Generated by Django 4.1.7 on 2023-05-01 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dependencia', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_dependencia', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_envio', models.PositiveIntegerField(unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_factura', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='Usuarios.dependencia')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_usuario',
            new_name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='amigos',
            field=models.ManyToManyField(blank=True, to='Usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='Usuarios.usuario'),
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='Usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='envio',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_recibidos', to='Usuarios.cuenta'),
        ),
        migrations.AddField(
            model_name='envio',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_realizados', to='Usuarios.cuenta'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='dependencias', to='Usuarios.usuario'),
        ),
    ]
