# Generated by Django 4.1.9 on 2023-05-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_financiera_rename_usuario_cuenta_cuenta_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiera',
            name='fecha_limite_pago_1',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financiera',
            name='fecha_limite_pago_2',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financiera',
            name='fecha_limite_pago_3',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
