# Generated by Django 4.1.7 on 2023-05-01 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_dependencia_envio_transaccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha_transaccion'], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='saldo',
            new_name='saldo_usuario',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='usuario',
            new_name='usuario_cuenta',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='nombre',
            new_name='nombre_dependencia',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='saldo',
            new_name='saldo_dependencia',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='ultima_actualizacion',
            new_name='ultima_actualizacion_dependencia',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='usuarios',
            new_name='usuarios_dependencia',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='destino',
            new_name='destino_cuenta',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='estado',
            new_name='estado_envio',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='fecha',
            new_name='fecha_envio',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='monto',
            new_name='monto_envio',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='origen',
            new_name='origen_cuenta',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='dependencia',
            new_name='dependencia_origien',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='fecha',
            new_name='fecha_transaccion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='fecha_vencimiento',
            new_name='fecha_vencimiento_transaccion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='info_factura',
            new_name='info_factura_dependencia',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='monto',
            new_name='monto_transaccion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='pagada',
            new_name='pagada_transaccion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='usuario',
            new_name='usuario_destino',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='amigos',
            new_name='amigos_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='apellidos_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='email_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='foto_perfil',
            new_name='foto_perfil_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='identificacion',
            new_name='identificacion_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres',
            new_name='nombres_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='tipo_dependencia',
            field=models.CharField(choices=[('Financiera', 'Financiera'), ('Otra', 'Otra')], max_length=50),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_semestre_estudiante', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creditos_registrados_estudiante', models.PositiveIntegerField()),
                ('semestre_actual_estudiante', models.PositiveIntegerField()),
                ('usuario_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
    ]
