# Generated by Django 4.1.9 on 2023-05-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_financiera_fecha_limite_pago_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='aumento_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='aumento_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='aumento_3',
            field=models.BooleanField(default=False),
        ),
    ]
