# Generated by Django 4.1.7 on 2023-05-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_alter_transaccion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='valor_semestre_estudiante',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
