# Generated by Django 4.1.9 on 2023-05-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_rename_info_factura_dependencia_transaccion_informacion_transaccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='origen',
            field=models.CharField(max_length=255),
        ),
    ]
